---
title: "fitting2"
author: "Julian Gottfried"
date: "2026-08-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r}
library(tidyverse)
setwd("~/Desktop/CME")
```

## Functions
```{r}
fitting <- function(statistics, counts) {
    factor <- 0
    loglik <- rep(0, 100 * 100)
    for (j in unique(statistics$N)) {
        if (j == 0) next
        slimdata <- statistics %>% filter(N == j)
        slimI <- as.numeric(unname(table(factor(slimdata$I, levels = 0:(O-1)))))
        factor <- factor + log(factorial(sum(slimI))) - sum(log(factorial(slimI)))
        slimfreq <- counts %>% filter(N == j)
        loglik <- loglik + apply(slimfreq[, 1:O], 1, \(x) sum(slimI * log(x)))
    }
    loglik <- loglik + factor + sum(dnbinom(statistics$N, size, p, log = T))
    cbind(loglik, slimfreq %>% select(c(R0, pi)))
}
```

## Hyperparams
```{r}
N <- 42
O <- 50

R0 <- seq(from = 0, by = 0.001, to = 0.1 - 0.001)
pi <- seq(from = 0, by = 0.0005, to = 0.05 - 0.0005)
mus <- 1:150

mu <- 97
var <- 516

p = mu / var
size = p * mu / (1 - p)

shape = size
scale = (1 - p) / p

mixture <- sapply(mus, \(x) pgamma(x, shape = shape, scale = scale) - 
           pgamma(x - 1, shape = shape, scale = scale))
const <- sum(mixture)
```

## CME data
```{r}
cmemat <- read.table("eitan_data/host_cme_matrix.txt", header = T, sep = "\t")
cmes <- colnames(cmemat %>% select(-host_id))
cmemat$aid <- str_split(cmemat$host_id, "_", simplify = T)[, 1]
cmemat$genome <- str_split(cmemat$host_id, "_", simplify = T)[, 2]
hostdat <-  read.table("eitan_data/hosts.txt", header = T, sep = "\t")
cmemat <- left_join(cmemat, hostdat %>% select(species, genus, family, host_id), by = "host_id")
cmetab <- read.table("eitan_data/cme_table.txt", header = T, sep = "\t")
cmedat <- cmemat %>% 
    group_by(aid, species) %>% 
    summarize_at(cmes, \(x) sum(x) != 0) %>% 
    select(-species) %>% 
    pivot_longer(cols = -aid, names_to = "cme") %>% 
    group_by(cme, aid) %>% 
    summarize(count = sum(value), .groups = "drop")
```

## N and I data
```{r}
fams <- cmemat %>% filter(c4) %>% pull(family) %>% unique
Nstats <- cmemat %>% filter(family %in% fams) %>% 
    group_by(aid) %>% select(aid, species) %>%
    distinct %>% summarize(N = n())
Istats <- cmemat %>% filter(c4) %>% group_by(aid, species) %>% 
        summarize(n = n()) %>% summarize(I = n())
statistics <- left_join(Nstats, Istats, by = "aid")
statistics <- rbind(statistics,
                    data.frame(aid = unique(hostdat$aid), 
                               N = 0, I = NA)[!(unique(hostdat$aid) %in% statistics$aid), ])
statistics[is.na(statistics)] <- 0
statistics <- statistics %>% select(-aid)
```

## Convert simulations to correct format
```{r}
converter <- function(i) {
    tmpcounts <- t(read.csv(paste0("results/counts_", i,".csv"), header = F))
    mixed <- matrix(0, length(pi), 8002)
    for (j in 1:length(pi)) {
        mixed[j, 1:8000] <- apply(tmpcounts[(1:150) + 150 * (j - 1), 1:8000], 2, 
              \(x) sum(x * mixture / const))
        
    }
    mixed[, 8001] <- R0[i]
    mixed[, 8002] <- pi
    shapely <- matrix(0, 100 * 160, 53)
    for (j in 1:160) {
        shapely[100 * (j - 1) + (1:100), 51] <- j
        shapely[100 * (j - 1) + (1:100), c(1:50, 52:53)] <-
            as.matrix(mixed[, c(50 * (j - 1) + (1:50), 8001:8002)])
    }
    colnames(shapely) <- c(paste0("X", 1:50), "N", "R0", "pi")
    shapely
}

shapeliest <- matrix(0, 16000 * 100, 53)
for (i in 1:100) {
    print(i)
    shapeliest[(1:16000) + 16000 * (i - 1), ] <- converter(i)
}
shapeliestdf <- data.frame(shapeliest)
colnames(shapeliestdf)[51:53] <- c("N", "R0", "pi")
write_csv(shapeliestdf, "c4_marc_2.csv")
```

## Fitting
```{r}
counts <- read_csv("c4_marc_2.csv")
counts[, 1:O] <- counts[, 1:O] + 1 / 10
divider <- rowSums(counts[, 1:O])
counts[, 1:O] <- apply(counts[, 1:O], 2, \(x) x / divider)
    
logliks <- fitting(statistics, counts)

getinterval <- function(var) {
    profiled <- logliks %>% group_by(!!!syms(var)) %>% summarize(loglik = max(loglik))
    colnames(profiled) <- c("var", "loglik")
    profiled$interval <- 2 * (max(logliks$loglik) - profiled$loglik) <= qchisq(0.95, 1)
    bounds <- range(unlist(profiled$var)[profiled$interval])
    profiled$interval <- with(profiled, ifelse(var >= bounds[1] & var <= bounds[2], T, F))

    hat <- unlist(logliks[var])[which.max(logliks$loglik)]
    med <- median(range(profiled$var[profiled$interval]))
    
    isR0 = var == "R0"
    plot <- profiled %>%
        ggplot(aes(x = var * mu ^ isR0, y = loglik, color = interval)) +
        geom_point(shape = 1, stroke = 0.8) +
        geom_vline(xintercept = med * mu ^ isR0, linetype = 2, color = "#6eecff") +
        scale_color_manual(values = c("black", "#ff4da3")) +
        guides(color = "none") +
        xlab(var) + ylab("loglik") +
        theme_classic() +
        theme(text = element_text(size = 12, family = "mono"))
    
    list(plot, as.numeric(hat), med)
}

getinterval("R0")[[1]]
getinterval("pi")[[1]]

R0hat <- round(getinterval("R0")[[2]], 4)
pihat <- round(getinterval("pi")[[2]], 5)
```

## Examining c4
```{r}
plotcounts <- counts %>% filter(round(R0, 4) == R0hat, round(pi, 4) == pihat)

gatherNI <- colSums(plotcounts[sapply(statistics$N, \(x) which(Ns == x)), 1:O])
gatherNI <- gatherNI / sum(gatherNI)

cmedat %>%
    filter(cme == "c4") %>% pull(count) %>% 
    factor(levels = 0:(O-1)) %>% table %>% data.frame %>% 
    rename(count = '.', freq = Freq) %>% 
    mutate(count = as.numeric(count) - 1, 
           freq = freq / sum(freq)) %>% 
    ggplot(aes(x = count, y = freq)) +
    geom_col(width = 1, color = "black", fill = "white")+
    ylim(0, 1) + xlim(-1, 20) +
    theme_classic() +
    ggtitle("c4") +
    theme(text = element_text(size = 12, family = "mono"),
          legend.position = "bottom")

data.frame(count = 0:(O - 1), freq = gatherNI[1:O]) %>% 
    ggplot(aes(x = count, y = freq)) +
    geom_col(width = 1, color = "black", fill = "white")+
    ylim(0, 1) + xlim(-1, 20) +
    theme_classic() +
    ggtitle("best fit") +
    theme(text = element_text(size = 12, family = "mono"),
          legend.position = "bottom")
```

Mine, 2 plug-ings: l = -263.37; AIC = 534.74
Marc's, 42 plug-ins: l = -220.52; AIC = 529.04
Marc's, 2 plug-ins: l = -269.83; AIC = 547.61
