---
title: "fitting"
author: "Julian Gottfried"
date: "2026-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set-up
```{r}
library(tidyverse)
setwd("~/Desktop/CME")
```

## Local sim functions
```{r}
birth <- function(fX, alpha, dt) rpois(1, fX * alpha * dt)
death <- function(X, dt) rbinom(1, X, 1 - exp(-dt))
FOI <- function(R0, S, I, dt) {
    if (S == 0 && I == 0) return(0)
    rbinom(1, S, 1 - exp(-R0 * I / (S + I) * dt))
}

singlerun <- function(S0, I0, R0, alpha, f, G, dt) {
    S <- rep(0, G)
    I <- rep(0, G)
    S[1] <- S0
    I[1] <- I0
    for (i in 2:G) {
        muSI <- FOI(R0, S[i - 1], I[i - 1], dt)
        
        S[i] <- S[i - 1] - muSI
        I[i] <- I[i - 1] + muSI
        
        S[i] <- S[i] + birth(1 - f, alpha, dt) - death(S[i], dt)
        I[i] <- I[i] + birth(f, alpha, dt) - death(I[i], dt)
    }
    c(S, I)
}

plotsingle <- function(result, G) {
    data.frame(time = c(1:G, 1:G), size = result, state = c(rep("S", G), rep("I", G))) %>%
        mutate(state = factor(state, levels = c("S", "I"))) %>%
        ggplot(aes(x = time, y = size)) +
        geom_line() +
        facet_wrap(~state) +
        theme_classic() +
        theme(text=element_text(size=12,family="mono"),
              legend.position = "bottom")
}
```

## Grid parameters
```{r}
beta <- seq(from=0,by=0.05,to=4.95)
mu <- seq(from=0,by=1,to=99)
p <- seq(from=0,by=0.001,to=0.099)
```

## Aggregate cluster sims
```{r}
counts <- NULL
for (i in 1:100) {
    print(i)
    countstmp <- data.frame(t(read.table(paste0("JLresults4/counts_",i,".csv"), sep=",")))
    countstmp$beta <- beta[i]
    countstmp$mu <- 0
    countstmp$p <- 0
    for (j in 1:100) {
        for (k in 1:100) {
            idx <- 100 * (j - 1) + k
            countstmp$mu[idx] <- mu[j]
            countstmp$p[idx] <- p[k]
        }
    }
    counts <- rbind(counts, countstmp)
}
write_csv(counts, "results4.csv")
```

## Convert counts
```{r}
counts <- read_csv("results4.csv")

# rowsums <- rowSums(counts %>% select(-c(beta, mu, p)))
sum(rowSums(counts %>% select(-c(beta, mu, p))) != 20000)
rowsums <- 20000
counts <- counts %>% mutate_at(paste0("X", 1:100), \(x) x / rowsums)

counts[10000, ] %>% 
    pivot_longer(starts_with("X"), names_to = "bin", values_to = "proportion") %>% 
    mutate(bin = as.numeric(str_remove(bin, "X")) - 1) %>%
    ggplot(aes(x = bin, y = proportion))+
    geom_point()+
    theme_classic()

finalbin <- counts %>% select(X21:X100) %>% rowSums
counts <- counts %>% select(-c(X21:X100)) %>% add_column(.before = "beta", X21 = finalbin)
```

## Get CME data
```{r}
cmemat <- read.table("eitan_data/host_cme_matrix.txt", header = T, sep = "\t")
cmes <- colnames(cmemat)[2:ncol(cmemat)]
cmemat$subject <- str_split(cmemat$host_id, "_", simplify = T)[, 1]
hostdat <-  read.table("eitan_data/hosts.txt", header = T, sep = "\t")
cmemat <- left_join(cmemat, hostdat %>% select(species, genus, family, host_id), by = "host_id")

# cmedathost <- cmemat %>% 
#     select(-c(host_id, species)) %>% 
#     pivot_longer(cols = -subject, names_to = "cme") %>% 
#     group_by(cme, subject) %>% 
#     summarize(count = sum(value)) %>% 
#     ungroup
cmedatsp <- cmemat %>% 
    group_by(subject, species) %>% 
    summarize_at(cmes, \(x) sum(x) != 0) %>% 
    ungroup %>% 
    select(-species) %>% 
    pivot_longer(cols = -subject, names_to = "cme") %>% 
    group_by(cme, subject) %>% 
    summarize(count = sum(value)) %>% 
    ungroup
```

## Extraneous
```{r}
for (i in 1:length(cmes)) {
    cmemat[cmemat[, cmes[i]], c("subject", "species")] %>% 
        group_by(subject) %>% summarize(n = n()) %>% 
        pull(n) %>% mean
}
```

## Estimate p
```{r}
# Method that doesn't work
level = "family"
estp <- rep(0, length(cmes))
for (i in 1:length(cmes)) {
    infecting <- cmemat[, level][cmemat[, cmes[i]]]
    estp[i] <- length(unique(infecting)) / length(infecting)
}
ggplot(data.frame(estp),
       aes(x = estp))+
    geom_histogram(color = "white", fill = "black") +
    theme_classic()

# Method that may work
coarse = "family"
fine = "species"
estp <- rep(0, length(cmes))
for (i in 1:length(cmes)) {
    infecting <- cmemat[, cmes[i]][cmemat[, fine] %in% 
                hostdat[, fine][hostdat[, coarse] %in% 
                                    unique(cmemat[, coarse][cmemat[, cmes[i]]])]]
    estp[i] <- sum(infecting)/length(infecting)
}
ggplot(data.frame(estp),
       aes(x = estp))+
    geom_histogram(color = "white", fill = "black") +
    theme_classic()

# Snap to grid
closestp <- round(p[estp%/%0.001 + 1], 3)
ggplot(data.frame(closestp),
       aes(closestp))+
    geom_histogram(color = "white", fill = "black") +
    xlim(NA, 0.1)+
    xlab("f")+
    theme_classic()+
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")
```

## Do fitting without prior p
```{r}
pseudo = 0.01
pars <- counts %>% select(beta:p)
fits <- data.frame(cme = cmes, idx = 0, loglik = -Inf)
for (i in 1:length(cmes)) {
    print(i)
    tmpdat <- cmedatsp %>% filter(cme == cmes[i]) %>% pull(count)
    tmpdat <- table(tmpdat + 1)
    subset <- counts[, as.numeric(names(tmpdat))]
    loglik <- apply(subset, 1, \(x) sum(log(x + pseudo) * tmpdat))
    fits[i, ] <- c(cmes[i], which.max(loglik), max(loglik, na.rm = T))
}
write_csv(fits, "fits4sp.csv")
```

## Plot p fit
```{r}
fits <- read_csv("fits4sp.csv")
ggplot(pars[fits$idx, ], aes(x=p))+
    geom_histogram(color = "white", fill = "black")+
    xlab("f")+
    theme_classic()+
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")

ordering <- order(closestp, decreasing = T)
data.frame(x = 1:length(cmes), 
           priorp = closestp[ordering],
           estp = pars[fits$idx, ]$p[ordering]) %>% 
    pivot_longer(priorp:estp) %>% 
    ggplot(aes(x = x, y = value, color = name)) +
    scale_color_discrete(palette = c("#E0AB60", "#7DA2C9"), 
                         labels = c("estimated","calculated"),
                         name = "") +
    geom_point() +
    ylab("f") +
    xlab("CME") +
    theme_classic() +
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")

```

## Do fitting with prior p
```{r}
pseudo = 0.01
pars <- counts %>% select(beta:p)
fits <- data.frame(cme = cmes, idx = 0, loglik = -Inf)
for (i in 1:length(cmes)) {
    print(i)
    tmpdat <- cmedatsp %>% filter(cme == cmes[i]) %>% pull(count)
    tmpdat <- table(tmpdat + 1)
    idx <- (1:nrow(pars))[pars$p == closestp[i]]
    subset <- counts[idx, as.numeric(names(tmpdat))]
    loglik <- apply(subset, 1, \(x) sum(log(x + pseudo) * tmpdat))
    fits[i, ] <- c(cmes[i], idx[which.max(loglik)], max(loglik, na.rm = T))
}
```

## Plot parameter spread
```{r}
pars[fits$idx, ] %>% 
    group_by(beta, mu, p) %>% 
    summarize(count = n()) %>% 
    ungroup %>% 
    mutate(alphaI = mu * p, alphaS = mu * (1 - p)) %>%
    rename(R0 = beta, alpha = mu) %>% 
    ggplot(aes(x = R0)) +
    geom_histogram(color = "white", fill = "black")+
    ggtitle("parameter fits across CMEs") +
    theme_classic() +
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")
pars[fits$idx, ] %>% 
    group_by(beta, mu, p) %>% 
    summarize(count = n()) %>% 
    ungroup %>% 
    mutate(alphaI = mu * p, alphaS = mu * (1 - p)) %>%
    rename(R0 = beta, alpha = mu) %>% 
    ggplot(aes(x = alpha, y = R0)) +
    geom_point(aes(size = count), stroke = 0.5, alpha = 1, shape = 1) +
    scale_size(range = c(0.5, 10)) +
    ggtitle("parameter fits across CMEs") +
    theme_classic() +
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")

sum(pars[fits$idx, ]$mu != 0 & pars[fits$idx, ]$beta != 0)/nrow(fits)
sum(pars[fits$idx, ]$mu == 0 & pars[fits$idx, ]$beta != 0)/nrow(fits)
sum(pars[fits$idx, ]$mu != 0 & pars[fits$idx, ]$beta == 0)/nrow(fits)
sum(pars[fits$idx, ]$mu == 0 & pars[fits$idx, ]$beta == 0)/nrow(fits)

```

## Plot particular CMEs
```{r}
fits$cme[with(pars[fits$idx, ], beta == max(beta))]
fits$cme[with(pars[fits$idx, ], mu == 0 & beta != 0)]

tester <- "c4"
cmedatsp %>%
    filter(cme == tester) %>% 
    pull(count) %>% 
    table %>% 
    data.frame %>% 
    rename(count = '.', freq = Freq) %>% 
    mutate(count = as.numeric(count) - 1, freq = freq / sum(freq)) %>% 
    ggplot(aes(x=count, y=freq)) +
    geom_col(width = 1, color = "black", fill = "white")+
    xlim(-1,22)+ylim(0,1)+
    theme_classic() +
    ggtitle(tester) +
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")
counts[fits$idx[fits$cme == tester], 1:21] %>% 
    pivot_longer(everything(), names_to = "count", values_to="freq") %>% 
    mutate(count=as.numeric(str_remove(count,"X"))-1, freq = freq / sum(freq)) %>% 
    ggplot(aes(x=count, y=freq)) +
    geom_col(width = 1, color = "black", fill = "white")+
    xlim(-1,22)+ylim(0,1)+
    theme_classic() +
    ggtitle("best fit") +
    theme(text=element_text(size=12,family="mono"),
          legend.position = "bottom")
testpars <- pars[fits$idx[fits$cme == tester], ]
testpars
plotsingle(singlerun(100, 0,
                     testpars$beta,
                     testpars$mu, 
                     testpars$p,
                     25000, 0.05), 25000)
```

```{r}
alpha <- 0.1
i <- (0:21)
plot(alpha^i / (exp(alpha) * factorial(i)))

```

